import Toybox.Lang;
using Toybox.System;

// Generated by tools/languages.py. Do not edit by hand.
class FaceText {
    private var _months as Lang.Array<Lang.Array<Lang.String>>;
    private var _weekdays as Lang.Array<Lang.Array<Lang.String>>;
    private var _automatic as Lang.Array<Lang.String>;
    private var _perpetualA as Lang.Array<Lang.String>;
    private var _perpetualB as Lang.Array<Lang.String>;

    function initialize() {
        _months = [
        ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"],
        ["JANVIER", "FÉVRIER", "MARS", "AVRIL", "MAI", "JUIN", "JUILLET", "AOÛT", "SEPTEMBRE", "OCTOBRE", "NOVEMBRE", "DÉCEMBRE"],
        ["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"],
        ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
        ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
        ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
        ["いちがつ", "にがつ", "さんがつ", "しがつ", "ごがつ", "ろくがつ", "しちがつ", "はちがつ", "くがつ", "じゅうがつ", "じゅういちがつ", "じゅうにがつ"],
        ["イチガツ", "ニガツ", "サンガツ", "シガツ", "ゴガツ", "ロクガツ", "シチガツ", "ハチガツ", "クガツ", "ジュウガツ", "ジュウイチガツ", "ジュウニガツ"],
        ["", "", "", "", "", "", "", "", "", "", "", ""],
        ["GENNAIO", "FEBBRAIO", "MARZO", "APRILE", "MAGGIO", "GIUGNO", "LUGLIO", "AGOSTO", "SETTEMBRE", "OTTOBRE", "NOVEMBRE", "DICEMBRE"],
        ["JANUAR", "FEBRUAR", "MÄRZ", "APRIL", "MAI", "JUNI", "JULI", "AUGUST", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DEZEMBER"]
        ];
        _weekdays = [
        ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"],
        ["DIM", "LUN", "MAR", "MER", "JEU", "VEN", "SAM"],
        ["DOM", "LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB"],
        ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
        ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],
        ["日", "月", "火", "水", "木", "金", "土"],
        ["にち", "げつ", "か", "すい", "もく", "きん", "ど"],
        ["ニチ", "ゲツ", "カ", "スイ", "モク", "キン", "ド"],
        ["", "", "", "", "", "", ""],
        ["DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"],
        ["SON", "MON", "DIE", "MIT", "DON", "FRE", "SAM"]
        ];
        _automatic = ["AUTOMATIC", "AUTOMATIQUE", "AUTOMÁTICO", "自动", "自動", "自動", "じどう", "ジドウ", "", "AUTOMATICO", "AUTOMATIK"];
        _perpetualA = ["PERPETUAL", "PERPÉTUEL", "PERPETUO", "万年", "萬年", "永久", "えいきゅう", "エイキュウ", "", "PERPETUO", "EWIGER"];
        _perpetualB = ["CALENDAR", "CALENDRIER", "CALENDARIO", "日历", "日曆", "暦", "こよみ", "コヨミ", "", "CALENDARIO", "KALENDER"];
    }

    function month(languageId as Lang.Number, monthNumber as Lang.Number) as Lang.String {
        return _months[languageId - 1][monthNumber - 1];
    }

    function weekday(languageId as Lang.Number, dayOfWeek as Lang.Number) as Lang.String {
        return _weekdays[languageId - 1][dayOfWeek - 1];
    }

    function automatic(languageId as Lang.Number) as Lang.String {
        return _automatic[languageId - 1];
    }

    function perpetualLine(languageId as Lang.Number, line as Lang.Number) as Lang.String {
        if (line == 0) {
            return _perpetualA[languageId - 1];
        }
        return _perpetualB[languageId - 1];
    }

    static function resolve(setting, systemLanguage) as Lang.Number {
        if (setting != null && setting != 0) {
            var chosen = setting;
            if (chosen < 1 || chosen > 11) {
                return 1;
            }
            return chosen;
        }
        if (systemLanguage == System.LANGUAGE_FRE) { return 2; }
        if (systemLanguage == System.LANGUAGE_SPA) { return 3; }
        if (systemLanguage == System.LANGUAGE_CHS) { return 4; }
        if (systemLanguage == System.LANGUAGE_CHT) { return 5; }
        if (systemLanguage == System.LANGUAGE_JPN) { return 6; }
        if (systemLanguage == System.LANGUAGE_ITA) { return 10; }
        if (systemLanguage == System.LANGUAGE_DEU) { return 11; }
        return 1;
    }
}
